language: python
python:
  - "3.7"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - pycodestyle --statistics --exclude=wsgi.py *.py
  - pycodestyle --statistics edid_parser/
  - pycodestyle --statistics frontend/
  - shopt -s globstar && pylint --reports=n *.py edid_parser/**/*.py frontend/**/*.py
  - coverage run --source=edid_parser edid_parser/tests.py
  - coverage run -a --source=frontend manage.py test frontend.django_tests
  - coverage run -a --source=frontend manage.py test frontend.selenium_tests
after_success:
  - coveralls
